### ISSUE TITLE
Impossible to hide CS-Script's main panel

### ISSUE THREAD

**Issue by dinkumoil** [oleg-shilo/cs-script.npp#16]
After CS-Script's main panel has switched to be visible it is not possible to switch it back to be invisible. Also the toolbar button doesn't reflect the panel's state, the toolbar button is always "Not pressed".

Npp version: 7.5.5 64-Bit
CS-Script version: 1.7.8.0 64-Bit

Same problem with 32-Bit versions. This bug was introduced around a year ago.

**Comment by dinkumoil** [comment]
Indeed, I meant toggling the plugin panel visibility by the plugin button/menu (case 2). Case 1 I completly overlooked and I understand the difficulties.

> I will restore the toggling in the incoming (in a few days) release.

This would be fine (seems like you did already). Thank you in advance.

> The problem is that Npp does not offer any API for determining if the panel is visible at the time of clicking the "toggle" button.

I have installed the [MarkdownViewer++](https://github.com/nea/MarkdownViewerPlusPlus) plugin too. It also provides a toolbar button to toggle its panel. This plugin is able to sync the status of its toolbar button and clicking the panel close button (your case 1). Might be interesting for you.

**Comment by oleg-shilo** [comment]
I had a look at MarkdownViewer++, txs. 
BTW a very useful plugin. It is using `override void WndProc` to detect panel closing. A hardcore approach but completely justified in this case.

I have reworked the current approach and now CS-Script plugin uses the same technique to detect the panel closing.

**Comment by oleg-shilo** [comment]
The release is now available: https://github.com/oleg-shilo/cs-script.npp/releases/tag/v1.7.9.0

**Comment by dinkumoil** [comment]
Thanks, that was fast.  :1st_place_medal:
