### ISSUE TITLE
 Feature request to support DLL building from Notepad++

### ISSUE THREAD

**Issue by oleg-shilo** [oleg-shilo/cs-script.npp#19]
_Moved from https://github.com/oleg-shilo/cs-script/issues/116_

It would be great if the -cd argument from the commandline version of cscs.exe were included in the GUI as well (and maybe all of the other commandline arguments too, if possible)

**Comment by oleg-shilo** [comment]
This shouldn't be difficult but what user experience do you have in mind?

Though you can already use any arguments via the `//css_args` directive:
```C#
//css_args -cd
using System;
using System.Text.RegularExpressions;

class Script
{
    static void Main(string[] args)
    {
       . . .
```  
And the outcome:
![image](https://user-images.githubusercontent.com/16729806/40779720-5dd5f820-6519-11e8-94c0-756c85c6a3be.png)

**Comment by mkosarekBHG** [comment]
Ah, I had not come across the `//css_args` directive yet. This makes things much easier. 

I was thinking, however, that it would be nice to have a `Build Dll` option in the menu dropdown. I find myself building Dlls quite often, but perhaps this is not a widespread issue.
