### ISSUE TITLE
Automatically select "First" occurrence of suggestion(s)

### ISSUE THREAD

**Issue by Samad-Shaikh** [oleg-shilo/cs-script.npp#23]
While using '.' or ctlr + space for auto-completion, please add functionality for automatically selecting the first occurance in "suggestion list" instead of pressing down arrow

**Comment by oleg-shilo** [comment]
I am not sure about this feature request. It is actually inconsistent with the Visual Studio user experience, which requires pressing 'up' or 'down' in order to select the first occurance in "suggestion list"

**Comment by oleg-shilo** [comment]
Implemented as an option.
Added config value `AutoSelectFirstSuggestion = false`

Will be available in the next release.
