### ISSUE TITLE
Notepad 7.5.7 is still trying to kick CS-Script 1.7.13.0 to the curb.

### ISSUE THREAD

**Issue by Graucsh** [oleg-shilo/cs-script.npp#24]

**Comment by MofX** [comment]
I had to manually remove all files from some old version of the plugin and reinstall it. After that it works again.

**Comment by oleg-shilo** [comment]
It's not only CS-Script. The changes to the hosting model in 7.5.7 affect every plugin with complext file structure. Even PluginManager is facing some issues (I talked to them).

Anyway I have tested it yesterday on the colleagues PC and N++ 7.5.7 x64 with manually installed x64 PluginManager has successfully pulled CS-Script 1.7.13 from the global plugins repo. Though it was a clean install.

If any prev version was installed PluginManager may leave the plugin primary assembly `CSScriptNpp.x64.dll` in the plugins folder. And this in turn will trigger N++ trying to load it at startup. This is confirmed as a PluginManager issue. 

Thus it is just a chain of unfortunate minor problems in N++ and its infrastructure that cripples CS-Script. 

Anyway, to fix the problem remove  `plugins\CSScriptNpp.x64.dll` and `plugins\CSScriptNpp` folder. After that install CS-Script as usual.

**Comment by Graucsh** [comment]
Interesting.  Thanks!

**Comment by chcg** [comment]
Now also the 32bit version is updated to 1.7.13 with the plugin manager dev list.

**Comment by oleg-shilo** [comment]
No 32bit plugin manager does not use GitHub for hosted repo but a custom one.  And this custom x86 repo at "https://npppm.bruderste.in/plugins" is not updated as quickly as the x64 one. Thus despite cs-script.npp v1.7.13 has been submitted in both the plugin manager x86 still retrieves the old v1.7.11 plugin. I just checked.

If you install that plugin it will run just fine but you will need to ignore the startup misleading N++ error message. I have already explained that.

Now, after starting N++ with the old v1.7.11 plugin you can go to the plugin AboutBox and update it to v1.7.13 from there via plugin own update mechanism. This way you will bypass PluginManager and fetch the plugin binaries directly from CS-Script GitHub page. Yes that....convoluted.

You can now probably understand my frustration with all this mess. I am really puzzles me to see how the authors of such successful product without even blinking slowly suffocating its most valuable feature - plugins. An the do it with the perseverance worthy of a better use.

**Comment by chcg** [comment]
@oleg-shilo Just the **dev** list of PM is updated right now(see checkbox under settings). it takes some days until that list is synced to the normal one to allow testing the changes before going alive for the majority of the users.
