### ISSUE TITLE
how can i stop this from pinging the internet while gaming?

### ISSUE THREAD

**Issue by DTG123** [oleg-shilo/cs-script.npp#27]
this is causing lag spikes while Im gaming is there a setting to stop the syntaxer.exe from connecting to the internet?

**Comment by oleg-shilo** [comment]
> connecting to the internet...

The _syntaxer_ never connects to the internet. 

_Syntaxer_ is a Roslyn-based intellisense server that uses sockets to communicate with clients. Though it is strictly using loopback address (localhost) to listen to. Thus it does not connect to the internet but simply listens to the local clients trying to connect to it. If it is something that you want to prevent then simply shutdown Notepad++.

**Comment by oleg-shilo** [comment]
If you have any concerns about _syntaxer_ you can find its code here: https://github.com/oleg-shilo/syntaxer
