### ISSUE TITLE
Notepad++ new Plugin Admin under testing - maybe its worth to participate in the discussion

### ISSUE THREAD

**Issue by dinkumoil** [oleg-shilo/cs-script.npp#29]
Since your CS-Script Notepad++ plugin is the most complex one I'm aware of, I want to point you to the ongoing discussion in the Notepad++ community forum about the newly introduced Npp Plugin Admin, see [here](https://notepad-plus-plus.org/community/topic/16494/new-built-in-plugin-admin-plugin-manager-is-ready). Further infos are obtainable [here](https://notepad-plus-plus.org/features/plugin-admin.html).

Currently Plugin Admin is under initial testing but it would bring some serious changes to plugins and would require some effort of plugin authors. Maybe its worth for you to participate in the discussion.

**Comment by oleg-shilo** [comment]
Fantastic. Thank you. 

I have learned from that discussion that there even more breaking changes are coming :(

To be honest I have no trust in N++ team willingness to accommodate the needs of the plugin vendors. Years of previous experience with them have shown how little regard they demonstrated to the need of the plugin developer 

And the latest breaking changes in the hosting model only confirm that. There going to be 
- yet another change in the hosting model, which will break any current plugin with sub-folders. 
- breaking change in the plugins' config persistence - now N++ will delete ALL setting on update.
- plugin update scheduling is rather puzzling. Plugin updates going to be even less frequent.  Meaning there is no way for for plugin vendors to address plugin. 

I have also posted the question there: https://notepad-plus-plus.org/community/topic/16494/new-built-in-plugin-admin-plugin-manager-is-ready/28, so may be some clarity will come...

But, I am afraid I will have to give up and completely divorce form PluginAdmin and use it only as a vehicle for bringing the CS-Script own custom plugin manager. 

It's rather disappointing. I am maintaining various plugins for VSCode, SublimeText3 and VisualStudio. And only in case Notepad++ it's always associated with constant pain. I hope they will eventually demonstrate some visionary qualities as other editor/IDE teams did.

**Comment by dinkumoil** [comment]
Thank you for participating in the discussion. I've informed some other plugin authors too. But like you I have only little hope that our interventions will change the opinion of the creator and main developer of Npp. But it has to be tried.

> now N++ will delete ALL setting on update

It is not that bad. When updating the Plugin Admin deletes the specific folder of the plugin in question (e.g. `<Npp-installation-folder>\plugins\CSScriptNpp`). The `config` folder stays untouched.

I close this issue because it has served its purpose.

**Comment by oleg-shilo** [comment]
Actually you are right. I interpreted quote below as the promise that "plugins\Config" will be deleted:
> The path of plugin config file should always be %APPDATA%\Notepad++ \plugins\Config since plugin folder will be erase entirely during its update.

My mistake. I posted the correction there.

Thank you. I really appreciate your input.
