### ISSUE TITLE
Custom (F5) launcher with arguments

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script.npp#30]
My application needs to be called like
`"APP.exe" -s "%1"`
where `-s` identifies the next argument being a script
and `"%1"` being a placeholder for the current document.

This is currently not supported by the [Custom (F5) launcher].

The call could also be `"APP.exe" -s "%CurrDoc%"` or whatever placeholder concept is best suited.

In addition, I'd prefer the [Custom (F5) launcher] configuration show a tooltip or example telling me that I have to use quotes in case `APP.exe` and/or `%1` is located in a path containing spaces.

**Comment by oleg-shilo** [comment]
Fixed. Will be available in the next release:

![image](https://user-images.githubusercontent.com/16729806/48656399-3b33e800-ea79-11e8-82c0-0bad1e72360c.png)
