### ISSUE TITLE
can't create new project 

### ISSUE THREAD

**Issue by MarcinStruglinski** [oleg-shilo/cs-script.npp#32]
I have a problem with creating a new project (bug in the attachment). I use Visula studio profesional 2015 and have installed cs-sscript by:
C: \> choco install cs-script
![bug](https://user-images.githubusercontent.com/35628643/50635988-b5023100-0f54-11e9-8c41-12b728d78057.png)

**Comment by oleg-shilo** [comment]
I have moved your post to a more appropriate thread: https://github.com/oleg-shilo/CS-Script.VSIX/issues/1

I have posted the fix suggestion there.
