### ISSUE TITLE
Auto-completion doesn't run the given css_precompiler first.

### ISSUE THREAD

**Issue by Irame** [oleg-shilo/cs-script.npp#33]
I have noticed that if I have specified a precompiler via the css flag ```css_precompiler``` and add some variables or usings there, they don't show up in the auto-completion.
It would be nice if there was the option to run some kind of precompiler before the auto-completion is generated.
In my particular case, I want to execute the script later in another program and want to emulate the environment of this program (like given imports and existing global variables).

**Comment by oleg-shilo** [comment]
Thank you for suggesting.
It's not a trivial feature to implement, but I will give it a try.
I will be revamping all plugins/extensions either end of Jan or end of Fab. Will see if can be done then.

**Comment by Irame** [comment]
Thanks for the quick response!
I'm looking forward to the changes, and hope you can implement it then.
I really like this project, keep up the great work!

**Comment by oleg-shilo** [comment]
Unfortunately, it is too difficult to do and also it would impact the auto-completion and the whole UX. I am trying to imagine what would it be if before popping up the suggestion box auto-completion will need to execute a pre-script that is accessing some online resources.

The same applies to resolving NuGet imports for your script.

Thus the IDE style approach is to stay: aoutocompletin incorporated any pre-processing outcome but pre-processing itself needs to be triggered by the user explicitly. IE build request - F7, Run request - F5.

Closing this issue now
