### ISSUE TITLE
Intercept StdOut for Build Output only.

### ISSUE THREAD

**Issue by vtictor** [oleg-shilo/cs-script.npp#35]
Hi,
Is it possibly to enable "intercept stdout" only for build? 
If I developing console app, that use user input I must uncheck it, because "intercept" can't handle it, but if error occurs I must check it to see error message.

**Comment by oleg-shilo** [comment]
It is a defect.

F7 supposed to automatically intercept build messages:
![image](https://user-images.githubusercontent.com/16729806/52197969-75ad6400-28b5-11e9-92c5-e39075c32004.png)

WIll be fixed in the very next release.

Thank you for reporting.

**Comment by oleg-shilo** [comment]
Can you please check that `DefaultSearchDirs=%csscript_inc%` does not have a pipe character at the end. It did on my machine:
_open settings_
![image](https://user-images.githubusercontent.com/16729806/52206867-a8fcec80-28cf-11e9-9715-fc4007d5b7c5.png)

_Remove the pipe character_

![image](https://user-images.githubusercontent.com/16729806/52206896-c336ca80-28cf-11e9-9198-f63635e8f803.png)

**Comment by vtictor** [comment]
In my case param "DefaultSearchDirs="  is empty.
Also, F7 do not handle any error. 
And i forgot to notice, I use Notepad++ v7.5.6, if it meters.

**Comment by oleg-shilo** [comment]
I am away right now so it's a bit difficult to respond promptly. 

I have installed the fresh copy of N++ and had exactly the problem you are describing. Though just opening and modifying the the setting file (saving is also enough)  effectively normalized the settings content and this in turn has fixed the problem. Meaning that my faulty setting file is gone now.

Thus can you please send me your setting file as may be it can still trigger the problem.

**Comment by vtictor** [comment]
`[Generic]
ShowProjectPanel=False
ShowOutputPanel=False
DebugAsConsole=True
HandleSaveAs=True
ShowLineNuberInCodeMap=False
ShowDebugPanel=False
WordWrapInVisualizer=True
ListManagedProcessesOnly=True
RunExternalInDebugMode=True
StartDebugMonitorOnScriptExecution=False
BlockLocalDebugOutputContaining=onecoreuap\inetcore\{NL}mincore\com\{NL}SHIMVIEW: ShimInfo(Complete)
CustomAsyncHost=
SyncSecondaryPanelsWithProjectPanel=True
OutputPanelCapacity=10000
HotkeyDocumentsExclusions=.cmd;.bat;.test
NavigateToRawCodeOnDblClickInOutput=False
QuickViewAutoRefreshAvailable=False
InterceptConsole=False
InterceptConsoleByCharacter=False
UseEmbeddedEngine=True
ReleaseNotesViewedFor=1.7.24.0
ScriptHistory=C:\Users\vi\Documents\monoProjects\helloworld\helloworld\Program.cs|
DebugStepPointColor=Yellow
DebugStepPointForeColor=Black
SciptHistoryMaxCount=10
CollectionItemsInTooltipsMaxCount=15
CollectionItemsInVisualizersMaxCount=1000
DebugPanelInitialTab=2
LocalDebug=True
BreakOnException=False
ShowOpenInVsAlways=False
ReloadActiveScriptOnRun=True
UpdateAfterExit=False
LastUpdatesCheckDate=2019-02-05
CheckUpdatesOnStartup=True
UseTogglingPanelVisibility=True
CheckPrereleaseUpdates=False
VbCodeProvider=CSSCodeProvider.v4.0.dll
ScriptsDir=C:\Users\vi\Documents\C# Scripts
UseRoslynProvider=True
StartRoslynServerAtNppStartup=True
ImproveWin10ListVeiwRendering=True
HideDefaultAssemblies=True
RestorePanelsAtStartup=True
UpdateMode=custom
FloatingPanelsWarningAlreadyPropted=False
LastExternalProcessCpu=0
NativeAutoCompletionChecked=True
TargetVersion=v4.0.30319
CsSConsoleEncoding=utf-8
ClasslessScriptByDefault=False
DistributeScriptAsScriptByDefault=False
DistributeScriptAsWindowApp=False
DistributeScriptAsDll=False
[Intellisense]
UseArrowToAccept=True
UseTabToAccept=True
InterceptCtrlSpace=True
PostFormattingUndoCaretReset=True
CodeSnippetsEnabled=True
ShowQuickInfoInStatusBar=False
ShowQuickInfoAsNativeNppTooltip=False
IgnoreDocExceptions=False
SmartIndenting=True
VbSupportEnabled=True
DisableMethodInfo=False
DisableMethodInfoAutoPopup=False
AutoSelectFirstSuggestion=False
AutoSuggestOnOpenEndLine=False
FormatOnSave.v2=False
AutoInsertSingeSuggestion=False
FallbackFormatting=False
RoslynFormatting=True
RoslynIntellisense_v2=True
UseCmdContextMenu=True
GoToDefinitionOnCtrlClick=True
ContextMenuCommands=Go To Definition;Find All References;Auto-add missing 'usings';Rename... (Ctrl+R,R);Format Document
MemberInfoMaxCharWidth=100
DefaultRefAsms=System.Linq|System.Xml|System.Xml.Linq|System.Windows.Forms|System.Drawing|System.Core|Microsoft.CSharp
DefaultSearchDirs=
DefaultNamespaces=System.Collections.Generic, System.Collections, System.Linq, System.Xml.Linq, System.Windows.Forms, System.Xml, Microsoft.CSharp, System.Drawing
MemberInfoMaxLines=15
FormatAsYouType=True
`

**Comment by oleg-shilo** [comment]
Great, your settings brought the problem back. 
Investigating now...

**Comment by oleg-shilo** [comment]
Bad news. I misinterpreted my runtime conditions and your config file in fact does not trigger the problem. Unfortunately.  :o(

I suggest that you do the following steps to restet your N++ plugin environment:
- Ensure you use the latest _CS-Script.Npp_ v1.7.24.
- Ensure N++ is not running.
- Remove your settings file completely. Just in case if it has some setting that is invalid in your environment but OK in mine. 
- Start N++. This will create a fresh default settings file.

This should let you get to this state:

![image](https://user-images.githubusercontent.com/16729806/52553452-9f2b3a00-2e37-11e9-86b3-2102e3a46d8f.png)

**Comment by vtictor** [comment]
It worked.
But is it possible to auto run "analyse" before execute by F5?

**Comment by oleg-shilo** [comment]
It is and it is what is happening. F5 builds .NET assembly from the script code and executes it. F7 does the same thing but without the execution.
