### ISSUE TITLE
How to enable unsafe code

### ISSUE THREAD

**Issue by RexProg** [oleg-shilo/cs-script.npp#4]
Hello
I am trying to use the unsafe code but it's have error CS0227 ("Unsafe code may only appear if compiling with /unsafe")
What is the purpose of this message?
What can I do?

> csscript is perfect :+1:

**Comment by oleg-shilo** [comment]
The unsafe is a compiler mode so it is enabled via direct compiler options, which you can pass with `//css_co` directive.
```C#
//css_co /unsafe
using System;
...
```

BTW, I am glad you like cs-script and I want to let you know that the plugin for VSCode is already available. And in a few days (or so) there will be a major upgrade to it that will bring seamless C# 7 to both Win and Linux.
