### ISSUE TITLE
Cant Compile with Unsafe Code

### ISSUE THREAD

**Issue by jaredaj3** [oleg-shilo/cs-script.npp#40]
I am trying to compile a project that needs to use the unsafe keyword. However the compiler is sending an error(CS0227) whenever I do. I looked this error up and it seems that the usual fix to this is to change a setting to allow unsafe to be used(if this was visual studio). However i don't see where I can change this in this plugin. Any help on getting this to work would be appreciated.

**Comment by oleg-shilo** [comment]
You will need to pass compiler option `unsafe`.

In Visual Studio you do it indirectly, by ticking the checkbox "Allow unsafe code". In CS-Script you specify the option directly in the code with the "compiler option" directive (e.g. `//css_co -unsafe` )

![image](https://user-images.githubusercontent.com/16729806/59747992-80ddbb00-92bd-11e9-84e0-68dde58db586.png)

**Comment by jaredaj3** [comment]
Thanks it works!
