### ISSUE TITLE
Unable to Manually Install

### ISSUE THREAD

**Issue by ColetronEngineering** [oleg-shilo/cs-script.npp#46]
Instructions for manual install are unclear.  I have the .zip file with CSScriptNpp file folder and CSScriptNpp.dll.  Where do I go from here to manually install the plug?
![example](https://user-images.githubusercontent.com/9848172/88198362-9f755a80-cc11-11ea-86e8-5956c56a8b54.PNG)

**Comment by oleg-shilo** [comment]
As per instructions here: https://github.com/oleg-shilo/cs-script.npp/wiki/Manual-Installation
you should put the content in the Notepad++ 'plugis' folder, which is "%ProgramFiles%\Notepad++\plugins". Unless Npp team has changed it :)
