### ISSUE TITLE
how to set breakpoint

### ISSUE THREAD

**Issue by crippler123** [oleg-shilo/cs-script.npp#47]
Hi
How do I set breakpoints?

**Comment by oleg-shilo** [comment]
F9

**Comment by crippler123** [comment]
Hi, thanks.
Where can I find detailed docomentation of debugging (using cs-script plugin)?

**Comment by oleg-shilo** [comment]
https://github.com/oleg-shilo/cs-script.npp/wiki/Script-Execution

Arguably more detailed description here: https://www.codeproject.com/Articles/694248/Sharpening-Notepadplusplus.
"Execution/Tracing/Debugging" section


But to put it simple, you need to 
- open the script file 
- place break point and hit Alt+F5
  if Npp screws hot keys then  use menu:
  
![image](https://user-images.githubusercontent.com/16729806/111763861-b41c0680-88f6-11eb-934e-54c82eaa069d.png)

---

TBH Npp is a great editor and it makes sense to use it for editing. Debugging with it was great as an alternative to Visual Studio. But with the availability of VSCode (+ it is portable) I would rather use for debugging VSCode with the CS-Script extension: https://marketplace.visualstudio.com/items?itemName=oleg-shilo.cs-script#:~:text=CS-Script%20-%20VSCode%20Extension%20(CS-Script.VSCode)%20Execution,%20debugging%20and,only%20and%20only%20if%20Mono%20hosting%20is%20enabled.
