### ISSUE TITLE
Exe path

### ISSUE THREAD

**Issue by crippler123** [oleg-shilo/cs-script.npp#48]
Hi

where can I define the exe path

**Comment by oleg-shilo** [comment]
Please elaborate.
What exe?

**Comment by crippler123** [comment]
after compiling test.cs, a test.exe is created.
where can I define the path of this exe?

**Comment by oleg-shilo** [comment]
The exe is created in the same location where your script is.
This location is not customizable so the exe will need to be copied manually.

With the plugin the idea is that you do not need to know where executable is if you are using Npp to run the scripts and only if you really want to build an exe then you trigger a dedicated workflow that opens the explored at the folder where the executable is. 

![image](https://user-images.githubusercontent.com/16729806/111777374-50e6a000-8907-11eb-8a43-d0945181c538.png)
