### ISSUE TITLE
How do I enable snippets?

### ISSUE THREAD

**Issue by it19862** [oleg-shilo/cs-script.npp#50]
How do I enable snippets?

**Comment by oleg-shilo** [comment]
:(
It's broken now. It supposed to be:
- type snippet name
- press alt+space
- select/accept snippet name in the autocompletion list

Now something prevents insertion of the tab snippet body. Not sure what. Will need to troubleshoot. Marking it as a defect.

**Comment by oleg-shilo** [comment]
It was a few problems there.

One that cannot be easily and reliably fixed is the competing user input workflows associated with autocompletion popup, Scintilla native autocompletion and tooltip support.

Thus a simplified snippet insertion model has been implemented.  From the next version snippet support will be restored and it will cover a simple insertion of the user predefined snippets.
![snippet](https://user-images.githubusercontent.com/16729806/127745825-525fb1da-fb6b-481e-b3d5-fb7a8d80167d.gif)
