### ISSUE TITLE
The Debug panel does not open when you reopen it 

### ISSUE THREAD

**Issue by it19862** [oleg-shilo/cs-script.npp#52]
Step -1. It works:
  - Notepad++ >> Plugins >> CS-script >> Debug Panel;
  - Result: Debug panel opened;
 
Step-2. Works:
  - I click [x] in the upper right corner of the Debug Panel to close the Debug Panel;
  - Result: The Debug Panel is closed;
 
 Step-3. **Problem!!!**
  - Notepad++ >> Plugins >> CS-script >> Debug Panel;
  - Result: Debug Panel not opened; **Problem !**

**Comment by oleg-shilo** [comment]
Thank you. Yes it is a defect.
Will be fixing it in the very next release.
In a mean time please use toolbar button instead. It "rotates" through all CS-Script panels:
![image](https://user-images.githubusercontent.com/16729806/124357887-1cea7d00-dc61-11eb-9ba3-608133673a0d.png)

**Comment by oleg-shilo** [comment]
Fixed. Will be available in the very next release
