### ISSUE TITLE
Where are the "Script library" files?

### ISSUE THREAD

**Issue by it19862** [oleg-shilo/cs-script.npp#53]
In the documentation on the website "cs-script.net" i found the section ["Script library"]( https://www.cs-script.net/cs-script/help-legacy/Script_library.html )

Where can I find the files that are described in cs-script/Lib, cs-script/Samples?
 
I use "cs-script" in Notepad++. I suspect that these files are used in other cases.

**Comment by oleg-shilo** [comment]
This is a legacy help you are referencing so it is applicable only to the older pre .NTE Core releases. Ironically it is exactly what you need now as I haven't migrated CS-Script.Npp on .NET Core just yet.

![image](https://user-images.githubusercontent.com/16729806/124917034-b1c0f200-e036-11eb-80f4-f6a9a0777c08.png)

You can find the samples in the extension pack distro of the last .NET Framework release:
https://github.com/oleg-shilo/cs-script/releases/download/v3.30.5.2/cs-script.ExtensionPack.7z
