### ISSUE TITLE
After pressing Ctrl+S the DC3 symbols appear

### ISSUE THREAD

**Issue by it19862** [oleg-shilo/cs-script.npp#55]
After pressing Ctrl+S the DC3 symbols appear.
Is this a problem or should I ignore it?
![MSACCESS_2021-07-07_13-31-41](https://user-images.githubusercontent.com/18245828/124744990-f9a52380-df27-11eb-87b2-8a04d16ba1f5.png)

**Comment by oleg-shilo** [comment]
It is  problem with the ScintillaTest control NPP is using or NPP itself. I noticed it too. It's not clear what it is causing but I suspect that NPP message loop does something naughty with the keyboard messages when plugins (like CS-script) hookup to the message loop via NPP hosting API.

I noticed that in most of the cases switching the doc tabs to another doc and back fixes it.

And since NPP is messing with the editor shortcuts (e.g. Ctrl+S) you can always use menu File->Save. Of course it is an inconvenience :(

**Comment by PeterSt1** [comment]
I just noticed that this (at least) happens when the Styler dialog from the UDL Settings is open (which is allowed to be open while continuing editing).

![image](https://user-images.githubusercontent.com/98317329/150767795-a553d2ee-2167-4e55-ac25-a01ee3060c6c.png)

**Comment by oleg-shilo** [comment]
Interesting. It confirmes what I said. This behaviour is not triggered by any plugin but NPP message processing. :(

**Comment by PeterSt1** [comment]
Yeah. Here's a similar situation I just found on StackOverflow. Only from 2010. :-)

[A few minutes ago I did a "Replace all" in my current document. Apparently, the dialog window informing me that "# occurrences were replaced" was hidden under another window, so I never closed it.](https://superuser.com/questions/211084/notepad-ctrl-s-does-not-save-instead-inserts-dc3-ctrl-f-inserts-ack)

I suppose the Messaging system is still waiting for messages, that overruling the Shortcuts (actually, undermining them).

**Comment by oleg-shilo** [comment]
I am convinced that having non-modal dialogs triggers that in one or another way. But I am not convinced it is the direct cause of it. Having non-modal dialogs is not an illegal SW dev pattern.

NPP API has a mechanism for subscription to the OS native messages. This mechanism is provided for plugins to get notifications on the IDE events including keystrokes. It's not ideal but works for most of the cases. I am guessing it has some flaw and possibly messes up with the keyboard messages when something (e.g. focus management) goes wrong. Thus it does not matter if it is a plugin or NPP own non-modal dialogue who is triggering it, we will see it from time to time.
