### ISSUE TITLE
What is OemPeriod in hotkeys?

### ISSUE THREAD

**Issue by it19862** [oleg-shilo/cs-script.npp#56]
There is a position in the hotkeys: 
Add missing 'using' - Ctrl+OemPeriod

What is `OemPeriod`?
How to implement `OemPeriod`?

**Comment by oleg-shilo** [comment]
This is how .NET calls a "dot" button.

**Comment by it19862** [comment]
@oleg-shilo 
Do I understand you correctly?
`Ctrl + OemPeriod` is `Ctrl + .`?
