### ISSUE TITLE
How to Add missing `using` using hotkeys?

### ISSUE THREAD

**Issue by it19862** [oleg-shilo/cs-script.npp#57]
I'm trying to add the missing `using` with: `Ctrl + .` ,  `Alt + U`.
Nothing is happening.
I have a code

```
using System;
using System.Diagnostics;
 
namespace Folder_NS_02
{
    public class Test
    {  
  void Main(string[] args)
  {
   List<string> ItemsLst = new List<string>(); 
  }  
 }
}
```
If I understand correctly, then after pressing `Ctrl + .` , `Alt + U` `CS-script.npp` will add to the code the line `using System.Collections.Generic;`.
I have nothing going on.

**Questions.**
1. Am I doing everything right?
2. How do I do this correctly?

**Comment by oleg-shilo** [comment]
The UX is very similar to the one that you have in VS:

`Ctrl+.`

![notepad2](https://user-images.githubusercontent.com/16729806/125091124-7a744300-e113-11eb-960b-3b452c90f6b4.gif)

`Alt+U`

![notepad](https://user-images.githubusercontent.com/16729806/125091179-88c25f00-e113-11eb-9898-2cd16cb1f598.gif)
