### ISSUE TITLE
How to Close a specific Tab(file)

### ISSUE THREAD

**Issue by pnjsinc** [oleg-shilo/cs-script.npp#62]
Greetings Oleg:

Love the project, I am using this to run a specialized compiler.
l am looking for a way to close a specific file or tab that is open.

Can you share with me how to accomplish this? 

Regards,
Pat

**Comment by oleg-shilo** [comment]
Ho @pnjsinc,

I am not sure I follow your question.

Are you asking how to close Notepad++ tab from the script you are running?

**Comment by pnjsinc** [comment]
Greetings Oleg:

That is correct.  After the compiler runs, it creates a file that shows the
code as it was compiled, minus the comments and compile directives.
This file is then opened by the compiler in npp.  I am wanting to close
this file before the code compiles again when needing to make additional
changes.

Thank you so much for the awesome tool.

**Comment by oleg-shilo** [comment]
Then I am afraid it's not a simple task. 

You see the script that you run is executed as a separate process. Thus you have very limited ability to control Notepad++.
And yet it is possible.

This is the pseudocode:
```
codefile = StripCommentsFrom(scriptFile)
nppWindowHandle = OpenInNpp(codefile)
nppTabIndex = SendMessage(nppWindowHandle, find_tab_with_file, codefile)
SendMessage(nppWindowHandle, close_tab, nppTabIndex)
```  

This is not a trivial task and it will require understanding the Scintilla API (a very old fashioned message-based interface).

**Comment by pnjsinc** [comment]
Thanks for the response, I was afraid that was going to be the case.

 

Thanks again for the great product.

 

Pat
