### ISSUE TITLE
Code Map tab from project panel is empty

### ISSUE THREAD

**Issue by FSS1313** [oleg-shilo/cs-script.npp#67]
Hi,
thanks for this very usefull project.
I was on version **1.7.24** and installed new version **1.7.29**. (with Notepad++8.3.3).

My feedbacks:

1. I noticed some slow down and lag, from editor. It happens quite regularly...Typically, to switch from a file to another file (click on Tab file name), to type text, to do an action...
2. I have no more autocompletion (ctrl+space) (option is disabled in Notepad++ settings to use autocompletion from CS-script plugin) and no more syntax information on mouse over...
3. I was using Code Map tab to  switch quickly between functions. Now, Code Map tab from project panel is empty. No more function list. Click on Refresh, always remains empty. 

![Code Map empty](https://user-images.githubusercontent.com/89262009/161225224-da537ec2-5027-469d-a247-7ef6c7264adc.png)

**Comment by oleg-shilo** [comment]
Thank you. Will have a look.
The very quick test revealed that I do not observe these problems in my environment. 
Though I am using .NET6 and globally installed CS-Script. Is it your case too?

**Comment by oleg-shilo** [comment]
![image](https://user-images.githubusercontent.com/16729806/161389572-6daa14a6-17a4-4864-bae8-c039b26e4da8.png)

![image](https://user-images.githubusercontent.com/16729806/161389592-44c4f653-fb2c-43dd-a0c1-a014d39947dc.png)

BTW, I highly recommend using `//css_ng csc` engine switch as it if so much faster :)

**Comment by FSS1313** [comment]
Even I use //css_ng csc I still have some slowdown or lag issue...

FYI, I have 32bits version of NPP...

.NET6 is installed and I installed CS-Script's update with extension installation manager.

I notice I haven't the same version of engine 3.28.9 instead of 4.4.2. ...

![CSScriptVersion](https://user-images.githubusercontent.com/89262009/161518832-121f3e7c-0a86-481f-acf6-ae29910c0a01.png)

**Comment by oleg-shilo** [comment]
Sorry, for the delay with the answer.
I am working on the next release of the extension that will be solely integrated with and dedicated to .NET. Thus many things will become simpler and even some configurations will be auto-generated.

Until then unfortunately the configuration needs to be done semi-automatically. I suspect that in your case there is something wrong with the syntaxer. I advise installing the latest version of .NET, CS-Script and CS-Syntaxer. You've done it for the first two but not sure about the syntaxer. You can install it from the Update tab of the Settings dialog.

After everything is configured properly your settings should look like this:
![image](https://user-images.githubusercontent.com/16729806/162647713-1eb83378-2578-41a1-bf04-18bca2525cd1.png)

Ther is another unknown variable in your case. You are running 32-bit version of Notepad++. I have not seen this type of deployment for probably a few years now. So not sure if it can or cannot impact anything. I only provide you with the info about scenarios that I tested on x64 systems.

**Comment by oleg-shilo** [comment]
Fixed now
