### ISSUE TITLE
Is it possible to add Unity 3D specific methods to Intellisense?

### ISSUE THREAD

**Issue by zenhund74** [oleg-shilo/cs-script.npp#70]
Hello, I'm still trying to configure an IDE like C# editor to have a comfortable programming environment for Unity 3D C# scripts.

So this plugin is amazing, when it comes to C# .Net Scripting. But can I add some of the Unity 3D Custom Classes for the auto completion in Intellisense? 

Kind regards,

**Comment by oleg-shilo** [comment]
My apologies. Somehow I have missed your post.

Yes it is possible. You just need to add the references to the Unity 3D libraries (like assembly reference in VS) and the IntelliSense should work right away. Providing Unity assemblies are compatible with .NET Core.

Addig references is as simple as adding `//css_ref my_assembly.dll` on the top of your script. You can find more details here: https://www.csscript.net/help/Directives.html
