### ISSUE TITLE
Missing debugger

### ISSUE THREAD

**Issue by dunha** [oleg-shilo/cs-script.npp#72]
Hi

I installed cs-script.npp 2.0.2 in Notepad++ 8.4.8 64 bit through the plugins, but had trouble showing the panels, and there is no debugger.
I removed the plugin and installed 2.0.3 from the releases. There is still no included debugger, but I have managed to get the panels displayed. There is only a toolbar button for the project panel.
I downloaded the standalone cs-script release and can see -wdbg folder in the distribution. Should this be included with the npp distro? (It doesn't work to copy it)

**Comment by oleg-shilo** [comment]
It's an interesting suggestion. 
The absence of the debugger is deliberate as .NET Core does not support the debugging technology that was used for this plugin.

Saying that cs-script now includes web debugger that is an experimental effort that I am reluctant to integrate with anything as it is not of industrial quality and is not tested by the army of developers.

If it changes in future then indeed it makes sense to at least let the button launch it. 
You can find the info on how to use WDBG here: https://github.com/oleg-shilo/cs-script/wiki/WDBG

**Comment by dunha** [comment]
Sorry, my bad. I missed the mention that it wasn't available for .Net core. I think that's why I stopped using it some years back. I'll try again with the old version.
Please excuse the noise.
Great project though

**Comment by oleg-shilo** [comment]
Not a problem. I also mad e a mistake. I dod not describe on the main page of this project that the debugger is only available for the .NET Framework.
I did it now though :)

**Comment by dunha** [comment]
All good. I now have npp 8 and cs-script 1.17.24 as per your advice, which works just like it did back in 2018. Thanks :)
