### ISSUE TITLE
CS-SCRIPT problem after rebuilding machine.

### ISSUE THREAD

**Issue by pnjsinc** [oleg-shilo/cs-script.npp#73]
Greetings:
Recently had to rebuild my machine, working on restoring NPP and CS-SCRIPT code that I use for automation.
Currently getting the error:
error CS0246: The type or namespace name ‘NppScripts’ could not be found (are you missing a using directive or an assembly reference?)

At the top of my scripts I have the following:
//css_ref C:\Program Files\Notepad++\plugins\NppScripts\NppScripts.dll
//css_ref C:\Program Files\Notepad++\plugins\NppScripts\NppScripts\NppScripts.asm.dll
using NppScripts
I tried changing it to the following as the old plugin was updated to Version 2.0.3.0:

//css_ref C:\Program Files\Notepad++\plugins\CSScriptNPP\CSScripts.dll
//css_ref C:\Program Files\Notepad++\plugins\CSScriptNpp\CSScriptNpp\CSScripts.asm.dll
using CSScripts;

Now it just states unable to find CSScripts…

Can someone please help, I am not able to figure out how to solve this, I use things like Editor.GetCurrentFilePath() which required the NppScripts using.

Thanks in advance for any and all feedback.
Regards,
Pat

**Comment by oleg-shilo** [comment]
CS-Script has two NPP plugins:
 - [NppScripts](https://github.com/oleg-shilo/scripts.npp) plugin for automating N++ via C# scripts executed by the CS-Script engine. 
 - [CS-Script - C# Intellisense (CSScriptNPP)](https://github.com/oleg-shilo/cs-scripts) plugin for executing generic C# scripts executed by the CS-Script engine.

NppScripts is no actively maintained and is no longer available via "Plugins Admin". Though it will most likely work just fine if installed manually from the plunging home page.

It seems to me that you are missing NppScripts but not CSScriptNPP

**Comment by oleg-shilo** [comment]
I am glad you solved it :)
